alias gst='git status'
alias ll='ls -l'
alias df='df -h'
alias du='du -h'

alias t='todo.sh'
alias ta='todo.sh add'
alias tl='todo.sh list'
alias td='todo.sh do'
alias te='vi ~/Dropbox/@todo/todo.txt'
